before_script:
  - npm rebuild node-sass
  - npm install

stages:
  - deploy

deployment:
  stage: deploy
  script:
    - npm run build
    - source ci/scripts/copy_build.sh
  only:
    - develop
    