before_script:
  - npm rebuild node-sass
  - yarn install

stages:
  - deploy

deployment:
  stage: deploy
  script:
    - yarn build
    - cp -r ./build/. /var/www/public/dashboard
  only:
    - develop
    
