sudo: required
dist: trusty
language: node_js
node_js:
  - "node"
before_install:
  - git checkout $TRAVIS_BRANCH
install:
  - source ci/scripts/install.sh
after_success:
 - source ci/scripts/git_config.sh
 - source ci/scripts/deploy.sh
