language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
- "./ci/before_install.sh"
install:
- "./ci/install.sh"
before_script:
- "./ci/before_script.sh"
script:
- "./ci/script.sh"
after_success:
- "./ci/deploy.sh"
after_script:
- "./ci/after_script.sh"
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
env:
  global:
  - APPNAME="flyve-mdm-ios"