version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: 
          name: "Install dependencies"
          command: source ci/scripts/install.sh

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: 
          name: "Build application"
          command: yarn build
      
  deploy:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: 
          name: "Install dependencies"
          command: source ci/scripts/install.sh

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: "Install Transifex Client and Files"
          command: source ci/scripts/transifex.sh
      
      - run: 
          name: "Build application"
          command: yarn build
      
      - run:
        name: "Create artifact"
        command: |
          zip -r ./build.zip build/* > /tmp/artifacts/build.zip
      
      - store_artifacts:
          path: /tmp/artifacts
          destination: build.zip

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
<<<<<<< HEAD
              only: feature/circle
=======
              only: develop
>>>>>>> 339fbb5... ci(deploy): send to transifex on develop branch
