version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10-stretch-node
    working_directory: ~/project-site
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    branches:
      only:
        - gh-pages
        - /feature/.*/
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-cache-{{ checksum "package-lock.json" }}
      - run:
           name: "Install environment"
           command:  source ci/installation.sh
      - save_cache:
          paths:
            - node_modules
          key: v1-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: "Run tests"
          command: npm test
      - run:
          name: "Run muffet"
          command: |
            muffet -f -t 30 http://flyve.org/web-mdm-dashboard/