files:
  include:
    - '_sass/3_level_generic/winstrap/**/*.s+(a|c)ss'
rules:
  "force-pseudo-nesting": 0
  "force-element-nesting": 0
  "no-important": 0
  "no-vendor-prefixes": 0
  "no-ids": 0
  "no-color-literals": 0
  "no-mergeable-selectors": 0
  "no-qualifying-elements": 0
  "force-attribute-nesting": 0
  "class-name-format": 0
  "no-duplicate-properties": 0
  "placeholder-in-extend": 0
  "empty-args":
    - 1
    - include: true
  "nesting-depth":
    - 1
    - max-depth: 3
